services:
  db-env:
    container_name: "db-env"
    build:
      context: ./
      dockerfile: Dockerfile.db
#    environment:
#      FLASK_APP: ./db/app_db.py
    volumes:
      - ${DATABASE_PATH}:/data
      - ./db/src:/src
      - ./db:/db
      - ${TRANSACTION_PATH}:/processed_transcripts
    ports:
      - "7001:7001"
 #   entrypoint: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    entrypoint: /db/entrypoint-db.sh
    networks:
      - w4a-network
  
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ${DATABASE_PATH}:/chroma/chroma
#    env_file:
#      - ./.env
    environment:
      CHORMA_SERVER_HOST: "0.0.0.0"
      CHROMA_SERVER_PORT: "8000"
      PERSIST_DIRECTORIY: "/chroma/chroma"
    ports:
      - "8000:8000"
    networks:
      - w4a-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] 
              capabilities: [gpu]

  w4a-app:
    image: "w4a"
    container_name: w4a-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./:/app
      - /srv/docker/whisper4all/whisper4all_projectai/transcription:/transcription
    networks:
      - w4a-network
    entrypoint: /app/entrypoint.sh

    
networks:
  w4a-network: